### ISSUE TITLE
Make slave_write_handler() static

### ISSUE THREAD

**Issue by tstana** [tstana/cubes-fw#10]
**NB: This issue applies to the code on the latest branch (`ramconfig-Histo-MPe`)**

The function `slave_write_handler()` is not called from anywhere outside the `msp_i2c.c` file. Make it static.

**Comment by Zethian** [comment]
@tstana Unsure how the program would react to this, as it is "called" from` mss_i2c.c `, but in a way that doesn't directly call the function (the function memory location is stored somewhere and then it's jumped to that adress, `this_i2c->slave_write_handler` in code).
Will test in april.
