### ISSUE TITLE
Solve all TODOs

### ISSUE THREAD

**Issue by tstana** [tstana/cubes-fw#21]
Steps to solve this issue:

1. Do a `grep` for the keyword `TODO` in the `cubes-fw/` folder. For example, using the Git Bash command line:
```
grep -rnH "TODO" .
```
2. Address each of the lines returned: either fix or remove.

**Comment by Zethian** [comment]
@tstana remaining TODOs are related to your code and ones you have put in, please resolve or instruct if I should try to apply them too.

**Comment by tstana** [comment]
Will handle myself (and check your fixes, too).

Thanks for handling them! Which branch are the fixes on?

**Comment by Zethian** [comment]
Remove_Ext

**Comment by tstana** [comment]
Issue #57 has been opened in relation to the three remaining (at the time of writing of this message) TODOs within `main.c`. It is worth noting that these are potentially not necessary to solve -- but good to be kept in mind.
