### ISSUE TITLE
I2C HardFault when program suspended in debug mode

### ISSUE THREAD

**Issue by Zethian** [tstana/cubes-fw#3]
Whenever the program is suspended while running, and has communication received through i2c from another part, program is entered into HardFault inf-loop and requires reboot to resolve.

Not critical to solve, as program should not be in suspended mode.
Add hardfault handler?

**Comment by tstana** [comment]
`HardFault_Handler()` finally added to `cubes-fw` code in commit 2a2ea56. Issue can be closed.
