### ISSUE TITLE
Implement HK ADC functionality

### ISSUE THREAD

**Issue by sonals301** [tstana/cubes-fw#30]
Implement Voltage, Current and Temperature readings from ADS1015

**Comment by tstana** [comment]
@sonals301 this has been merged to `rebinning`, then `master`. Please do one last sanity check before flashing the code on the new `master` to NVM. After that, go ahead and close this issue.

Stellar job with the HK-ADC implementation, congratulations!

**Comment by tstana** [comment]
HK-ADC code flashed to NVM of lab setups. Closing issue.
