### ISSUE TITLE
IRQ clash among HVPS, TIM64 and HK-ADC

### ISSUE THREAD

**Issue by sonals301** [tstana/cubes-fw#33]
Sort out IRQ clashes or malfunctioning among HVPS, TIM64 and HK-ADC by setting right NVIC priorities and ensure proper functioning for all components altogether

HVPS - UART0_IRQ
TIM64 is for DAQ timing - TIM1_IRQ
HK-ADC - I2C0_IRQ

As of now, without proper NVIC priority settings, MSS is getting hung waiting for interrupts from respective components in while() loops.

**Comment by tstana** [comment]
Issue solved and merged to `master`. Closing.
